export const AUTHENTICATED = 'AUTHENTICATED';
export const UNAUTHENTICATED = 'UNAUTHENTICATED';
export const TOKEN_EXPIRED = 'TOKEN_EXPIRED';

const AUTH_STATUS = Object.freeze({
  AUTHENTICATED: 'AUTHENTICATED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
});

export default AUTH_STATUS;
