const SLOT_STATUS = Object.freeze({
  AVAILABLE: 'AVAILABLE',
  OPEN_HOUR: 'OPEN_HOUR',
  PENDING: 'PENDING',
  PLANNING_OPEN_HOUR: 'PLANNING_OPEN_HOUR',
  PLANNING_SCHEDULE: 'PLANNING_SCHEDULE',
  APPOINTMENT: 'APPOINTMENT',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
});

export default SLOT_STATUS;
